
// Objective-C API for talking to the following Go packages
//
//	github.com/lwinch2006/FlutterGoApp/Services
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Services_FRAMEWORK_H__
#define __Services_FRAMEWORK_H__

#include "Services.objc.h"
#include "Universe.objc.h"

#endif
