// Objective-C API for talking to github.com/lwinch2006/FlutterGoApp/Services Go package.
//   gobind -lang=objc github.com/lwinch2006/FlutterGoApp/Services
//
// File is generated by gobind. Do not edit.

#ifndef __Services_H__
#define __Services_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class ServicesGreetingService;
@class ServicesMathService;

@interface ServicesGreetingService : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (NSString* _Nonnull)getGreeting;
@end

@interface ServicesMathService : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (long)getRandomNumber;
@end

#endif
